<template>
  <div>
    <div class="title">
      <h2>客家音樂篇</h2>
    </div>
    <hr>
    <p class="firstRow"></p>
    <h3>一、客家傳統歌謠</h3>

    <table rules="all" border="1" style="border:1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width:20%">名稱</th>
          <th style="width:20%">負責人</th>
          <th style="width:25%">地址/電話</th>
          <th>其他聯絡方式</th>
          <th style="width:25%">備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            台北市中原客家崇正會文山客家歌謠班
          </td>
          <td>
            班長<br>黃逢廣
          </td>
          <td>
            臺北市文山區福興路2號（興隆國小音樂教室）<br>02-9353616
          </td>
          <td>
            <a target="_" href="http://club.ntu.edu.tw/~club20433/haksong/sanko/teach.htm">連結</a>
          </td>
          <td>
            團練時間：19:30-21:30<br>團練地點：興隆國小音樂教室
          </td>
        </tr>
        <tr>
          <td>
            台北市中原客家崇正會祟正歌謠班
          </td>
          <td>
            班長<br>許瑞
          </td>
          <td>
            臺北市大安區信義路3段157巷11號4樓教室（台北市客家文化會館）<br>02-8788-4541
          </td>
          <td>
            <a target="_" href="https://blog.xuite.net/ho2104/blog">連結</a>
          </td>
          <td>
            團練時間：每週一17:00-19:00<br>團練地點：台北市客家文化會館
          </td>
        </tr>
        <tr>
          <td>
            台北市客家自強會樟新客家歌謠班
          </td>
          <td>
            戴紅櫻
          </td>
          <td>
            臺北市文山區一壽街22號9樓（樟新活動中心）<br>02-2936-7260
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>
            台北市客家長青會客家歌謠班
          </td>
          <td>
            理事<br>劉金霖
          </td>
          <td>
            臺北市大安區和平東路二段95號之1<br>02-2708-5995
          </td>
          <td>
            <a target="_" href="https://ssl.thcp.org.tw/connections/clubs?page=3">連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td>
            台北客家鄉音合唱團
          </td>
          <td>
            陳采玲
          </td>
          <td>
            臺北市萬華區國興路1巷4號9樓之4<br>02-2980-8613
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pg/TPHKC/about/?ref=page_internal">連結</a>
            <br><a target="_" href="mailto:chen_tsailing@yahoo.com.tw">連結</a>
          </td>
          <td>
            成立於2016年<br>團練時間：每週日14:00-17:00<br>團練地點：台北市客家文化會館
          </td>
        </tr>
        <tr>
          <td>
            台灣客家山歌團
          </td>
          <td>
            姜雲玉
          </td>
          <td>
            臺北市長安東路二段189號2樓之5<br>02-2771-0794
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/twhakka1991/">連結</a>
          </td>
          <td width="132">
            成立於1991年<br>團練時間：每週一19:30-21:30<br>團練地點：台北市客家文化會館
          </td>
        </tr>
        <tr>
          <td>
            全球客家聲韻歌劇團
          </td>
          <td>
            張堂珍
          </td>
          <td>
            臺北市北投區明德路174巷8號2樓<br>0933-056-319
          </td>
          <td>
            <a target="_" href="mailto:lifechang8@gmail.com">連結</a>
          </td>
          <td>
            團練時間：每週三14:00-17:00<br>團練地點：臺北市客家主題公園
          </td>
        </tr>
        <tr>
          <td>
            忠勤客家歌謠班
          </td>
          <td>
            彭維熙
          </td>
          <td>
            臺北市中華路二段293號B1樓（忠勤活動中心）<br>0937-920-246
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>
            忠義客家歌謠班
          </td>
          <td>
            李榮堂
          </td>
          <td>
            臺北市中華路二段315巷4弄1號（國盛活動中心）<br>02-2307-2265
          </td>
          <td></td>
          <td>
            團練時間：每週三19:30-21:30<br>團練地點：臺北市客家文化主題公園
          </td>
        </tr>
        <tr>
          <td>
            景美客家歌謠班
          </td>
          <td>
            陳錦月
          </td>
          <td>
            臺北市羅斯福路六段393號7樓（景行活動中心）<br>02-2937-5272
          </td>
          <td></td>
          <td>
            成立於2005年<br>上課時間：每週四14:30-16:30
          </td>
        </tr>
        <tr>
          <td>
            臺北市北區客家會石牌客家歌謠班
          </td>
          <td>
            班長<br>羅方蓉
          </td>
          <td>
            0936-060-607<br>02-2821-9075
          </td>
          <td>
            <!-- <a target="_" href="http://www.hakkaonline.com/article-1040-1.html">連結</a> -->
          </td>
          <td>
            成立於1996年<br>團練地點：臺北市大東路75號2樓
          </td>
        </tr>
        <tr>
          <td>
            臺北市新竹縣同鄉會三興客家歌謠班
          </td>
          <td>
            林桂英
          </td>
          <td>
            臺北市基隆路二段99號（三興國小）<br>0937-934-932
          </td>
          <td width="132">
            <a target="_" href="https://www.facebook.com/pg/Sanxingballadsclasses/about/?ref=page_internal">連結</a>
          </td>
          <td>
            成立於1990年<br>團練時間：每週五19:30-21:30<br>團練地點：三星國小視聽教室
          </td>
        </tr>
        <tr>
          <td>
            關渡客家歌謠班
          </td>
          <td>
            黃順平
          </td>
          <td>
            臺北市北投區知行路277號2樓<br>02-2809-9036
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>
            新北市客家美聲發展協會
          </td>
          <td>
            梁文剛
          </td>
          <td>
            新北市板橋區市民大道三段247巷7號3樓<br>02-2929-4679
          </td>
          <td width="132">
            <a target="_" href="https://www.hakka-associations.ntpc.gov.tw/files/15-1002-1671,c121-1.php">連結</a>
          </td>
          <td>
            成立於2003年
          </td>
        </tr>
        <tr>
          <td>
            桃園市芙韻合唱協會
          </td>
          <td>
            指導<br>游立佳
          </td>
          <td></td>
          <td>
            <a target="_" href="https://www.facebook.com/pg/hibiscusdiva/about/?ref=page_internal">連結</a>
          </td>
          <td>
            成立於2010年<br>每週五14:00-16:00<br>團練地點：山澗居（龍潭金龍路）
          </td>
        </tr>
        <tr>
          <td>
            桃園市客家文化歌謠協會
          </td>
          <td>
            理事<br>陳秀珠
          </td>
          <td>
            桃園市平鎮區義興里義民路214號2樓<br>03-494-9243
          </td>
          <td></td>
          <td width="132">
            成立於2007年<br>團練時間：每週四19:00-21:00<br>團練地點：桃園市平鎮區義興里集會所
          </td>
        </tr>
        <tr>
          <td>
            桃園縣客家民謠研究學會
          </td>
          <td>
            黃金通
          </td>
          <td>
            桃園市中壢區元化路165巷17號9樓<br>03-426-5648<br>0933-110-163
          </td>
          <td width="132"></td>
          <td>
            成立於2003年
          </td>
        </tr>
        <tr>
          <td>
            荷聲合唱團
          </td>
          <td></td>
          <td></td>
          <td>
            <a target="_" href="https://www.facebook.com/LotussoundFans/">連結</a><br>
            <a target="_" href="mailto:jeli4881@yahoo.com.tw">連結</a>
          </td>
          <td>
            團練時間：每週一、三中午<br>團練地點：國家中山科學研究院核研所演藝廳
          </td>
        </tr>
        <tr>
          <td>
            碧霞鄉土客家民謠劇團
          </td>
          <td>
            趙彩雲
          </td>
          <td>
            桃園市中壢區三光路158巷12號<br>03-492-0676<br>0912-671-732
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/LBCCTY/">連結</a>
          </td>
          <td>
            成立於2015年<br>團練時間：每週三14:00-16:00<br>團練地點：桃園市平鎮區義民廟
          </td>
        </tr>
        <tr>
          <td>
            財團法人新竹縣基督教客家福音協會
          </td>
          <td>
            白美月
          </td>
          <td>
            新竹縣竹東鎮自強路58號1樓<br>03-594-5546
          </td>
          <td>
            <a target="_" href="mailto:twhakka.chea@gmail.com">連結</a>
          </td>
          <td>
            成立於1978年<br>團練時間：每個月練習一次，於週二或四，依演出需求而定。
            <br>團練地點：新竹縣竹東鎮自強路58號1樓
          </td>
        </tr>
        <tr>
          <td>
            苗栗市玉華社區發展協會
          </td>
          <td>
            劉源順
          </td>
          <td>
            苗栗縣苗栗市玉清一街149號<br>0928-909-977（前任理事長）
          </td>
          <td>
            <a target="_" href="mailto:shun@mail2.ctsh.mlc.edu.tw">連結</a>
          </td>
          <td>
            成立於1985年
          </td>
        </tr>
        <tr>
          <td>
            苗栗市嘉盛社區發展協會
          </td>
          <td>
            總幹事<br>張永昌
          </td>
          <td>
            苗栗縣苗栗市嘉盛里3鄰嘉盛街187號<br>03-726-0309<br>0932-666-120
          </td>
          <td>
            <a target="_" href="mailto:miaolo.js@msn.hinet.net">連結</a>
          </td>
          <td width="132">
            成立於2012年<br>團練時間：每週五19:00-21:00<br>團練地點：嘉盛里社區發展中心
          </td>
        </tr>
        <tr>
          <td>
            苗栗縣大湖歌舞發展協會
          </td>
          <td>
            甘必成<br>張雲霞
          </td>
          <td>
            苗栗縣大湖鄉大湖村4鄰博愛路15號<br>03-799-1750<br>0912-675-665
          </td>
          <td>
            <a target="_" href="mailto:gan@taian.gov.com.tw">連結</a>
          </td>
          <td>
            成立於2005年<br>上課時間：每週二、五19:00-22:00<br>團練地點：大湖鄉公所老人文康中心3樓
          </td>
        </tr>
        <tr>
          <td>
            苗栗縣山城客家弦歌協會
          </td>
          <td>
            邱榮貴
          </td>
          <td>
            苗栗縣苗栗市維祥里維勝街62巷21弄12號<br>0920-600-046
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pg/Miaoli.hakka.association/about/?ref=page_internal">連結</a>
          </td>
          <td>
            成立於2007年<br>團練時間：每週四14:00-16:30<br>團練地點：苗栗火車站市場2樓
          </td>
        </tr>
        <tr>
          <td>
            苗栗縣苗栗市維祥社區發展協會
          </td>
          <td>
            理事<br>謝國章
          </td>
          <td>
            苗栗縣苗栗市維祥里17鄰光華街97號<br>03-735-8435<br>0932-565-111
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>
            南投縣埔里鎮客家文化發展協會
          </td>
          <td>
            曾子肅
          </td>
          <td>
            南投縣埔里鎮枇杷里樹人三街52號<br>04-9299-1799<br>0933-186-548
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/南投縣埔里鎮客家文化發展協會-Puli-Hakka-新版-1681221068828030/">連結</a>
          </td>
          <td>
            成立於2005年<br>團練時間：每週四14:30-16:30<br>團練地點：埔里鎮仁愛公園老人會館
          </td>
        </tr>
        <tr>
          <td>
            府城哈客合唱團
          </td>
          <td>
            謝佩芬
          </td>
          <td>
            臺南市崇明二十二街58號<br>0933-710-946
          </td>
          <td></td>
          <td width="132">
            成立於2004年<br>團練時間：每週四14:30-16:30<br>團練地點：臺南客家文化會館
          </td>
        </tr>
        <tr>
          <td>
            臺南市南瀛客家文化協會歌謠班
          </td>
          <td>
            謝錦梅
          </td>
          <td>
            臺南市新營區民權路96之27號<br>06-633-7627
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pg/台南市南瀛客家文化協會-116898431697699/posts/">連結</a>
          </td>
          <td>
            成立於2010年<br>團練時間：每週四19:00-21:00<br>團練地點：南瀛客家文化會館
          </td>
        </tr>
        <tr>
          <td>
            臺南市緣圓園客家樂舞團
          </td>
          <td>
            林宏峯
          </td>
          <td>
            臺南市南區新孝路102巷43號<br>0912-174-290
          </td>
          <td></td>
          <td>
            成立於2017年<br>團練時間：每週三09:00-11:00<br>團練地點：臺南市客家文化會館
          </td>
        </tr>
        <tr>
          <td>
            欣采樂綜藝團
          </td>
          <td>
            張素珠
          </td>
          <td>
            高雄市苓雅區四維四路186號<br>07-322-6677
          </td>
          <td>
            <a target="_" href="mailto:swiftlet@swiftlet.com.tw">連結</a>
          </td>
          <td width="132">
            成立於2006年<br>團練時間：每週四19:30-21:30<br>團練地點：高雄市博愛一路319號9樓
          </td>
        </tr>
        <tr>
          <td>
            美濃客家混聲合唱團
          </td>
          <td>
            藍勝生
          </td>
          <td>
            高雄市美濃區自強街一段391巷6號<br>0933-661-823
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/高雄市美濃混聲合唱團-491930940887705/">連結</a>
          </td>
          <td>
            成立於2005年<br>團練時間：每週四19:00-21:00
          </td>
        </tr>
        <tr>
          <td>
            美濃婦女合唱團
          </td>
          <td>
            團長<br>李雪光<br>行政總監<br>劉蘭英
          </td>
          <td>
            高雄市美濃區雙峰街18號<br>07-681-2179<br>0911-880-179
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/hklee0321/">連結</a>
          </td>
          <td width="132">
            成立於1990年<br>團練時間：每週三08:30-11:30<br>團練地點：高雄市美濃區雙峰街18號
          </td>
        </tr>
        <tr>
          <td>
            樂線綜藝團
          </td>
          <td>
            鍾鳳英
          </td>
          <td>
            高雄市三民區建工路433巷27號3樓<br>07-386-5208<br>0929-416-817
          </td>
          <td>
            <a target="_" href="http://kh8.khakka.org.tw/webeip/ht00567/kh8-class.asp">連結</a>
          </td>
          <td width="132">
            成立於2006年<br>團練時間：每週二19:30-21:30<br>團練地點：寶珠溝活動中心4樓
          </td>
        </tr>
        <tr>
          <td>
            屏東客家樂舞團
          </td>
          <td>
            林瑞輝
          </td>
          <td>
            屏東縣萬巒鄉（村）褒忠路183號<br>08-781-2456<br>0929-355-368<br>傳真：08-781-3291
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/PTHakka/">連結</a>
          </td>
          <td>
            成立於2002年
          </td>
        </tr>
        <tr>
          <td>
            屏東縣竹田鄉客家樂舞協會
          </td>
          <td>
            劉秋琴
          </td>
          <td>
            屏東縣竹田鄉竹南村潮州路42號<br>0983-508-779
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>
            屏東縣長治鄉客家民謠協會
          </td>
          <td></td>
          <td>
            屏東縣長治鄉潭頭村合興路124號<br>08-721-7930
          </td>
          <td width="132">
            <!-- <a target="_" href="https://socmap.pthg.gov.tw/pt1w/app/map?objid=3470503">連結</a> -->
          </td>
          <td>
            成立於1996年
          </td>
        </tr>
        <tr>
          <td>
            屏東縣高樹鄉客家樂舞協會
          </td>
          <td>
            張永雄
          </td>
          <td>
            屏東縣高樹鄉長榮村南昌路2之2<br>08-796-2136<br>0963-200-267
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>
            藍衫樂舞團
          </td>
          <td>
            鍾芳廉
          </td>
          <td>
            屏東縣萬巒鄉萬和村南進路54號<br>08-779-2055
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/藍衫樂舞團-Blue-Shirts-Music-and-Dance-Troupe-185867531445580/">連結</a>
          </td>
          <td width="132">
            成立於1993年<br>團練時間：每週五20:00-22:00<br>團練地點：屏東縣麟洛鄉麟趾村12鄰仁愛街39號
            <s> </s>
          </td>
        </tr>
        <tr>
          <td>
            花蓮客家合唱團
          </td>
          <td>
            李惠敏
          </td>
          <td>
            花蓮縣吉安鄉自立路9號<br>0933-997-800
          </td>
          <td>
            <a target="_" href="https://reurl.cc/QpQd0M">連結</a>
          </td>
          <td></td>
        </tr>
      </tbody>
    </table>
    <br>
    <h3>
      二、客家傳統器樂
    </h3>
    <table rules="all" border="1" style="border:1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width:20%">名稱</th>
          <th style="width:20%">負責人</th>
          <th style="width:25%">地址/電話</th>
          <th>其他聯絡方式</th>
          <th style="width:25%">備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            鄉音國樂團
          </td>
          <td>
            許瑞
          </td>
          <td>
            臺北市信義路三段157巷11號4樓<br>0921-831-786
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/hakkamelody/">連結</a>
          </td>
          <td>
            成立於2001年<br>團練時間：每週二18:30
          </td>
        </tr>
        <tr>
          <td>
            榮芳客家北管國樂團
          </td>
          <td>
            陳石榮
          </td>
          <td>
            新北市樹林區太平路89號<br>02-2681-8559
          </td>
          <td></td>
          <td>
            成立於2004年
          </td>
        </tr>
        <tr>
          <td>
            大華國樂文創團
          </td>
          <td>
            陳國芳
          </td>
          <td>
            桃園市八德區介壽路二段1022巷14號<br>03-365-4568<br>0935-025-143
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/大華國樂文創團陳國芳-1563159900469333/">連結</a>
          </td>
          <td>
            成立於2000年
          </td>
        </tr>
        <tr>
          <td>
            和成八音團
          </td>
          <td>
            袁久貴
          </td>
          <td>
            桃園市八德區霄裡里28鄰關路78號<br>0910-150-749
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/Hcg2232/">連結</a>
          </td>
          <td>
            成立於1979年
          </td>
        </tr>
        <tr>
          <td>
            田屋北管八音團
          </td>
          <td>
            田文光
          </td>
          <td>
            新竹縣竹北市民生街11巷7號<br>03-551-3320
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/TienWuBeiGuanBaYin/">連結</a>
          </td>
          <td>
            成立於1989年
          </td>
        </tr>
        <tr>
          <td>
            新竹北埔八音團
          </td>
          <td>
            彭峻暘
          </td>
          <td>
            新竹縣北埔鄉南興村南興街63號<br>0907-945-638
          </td>
          <td width="123">
            <a target="_" href="https://www.facebook.com/pages/category/Musician-Band/新竹北埔八音團-2044972268925287/">連結</a>
          </td>
          <td></td>
        </tr>
        <tr>
          <td width="75">
            關西祖傳隴西八音團
          </td>
          <td>
            彭金春<br>彭宏男
          </td>
          <td>
            新竹縣關西鎮
          </td>
          <td width="123"></td>
          <td width="151"></td>
        </tr>
        <tr>
          <td>
            苗栗陳家班北管八音團
          </td>
          <td>
            鄭榮興
          </td>
          <td>
            苗栗縣後龍鎮豐富里新東路47之1號<br>03-772-5099
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/MiaoliChenFamilyBeiguanBayinTroupe/">連結</a>
          </td>
          <td>
            成立於1983年
          </td>
        </tr>
        <tr>
          <td width="75">
            桃城樂府客家八音團
          </td>
          <td width="66"></td>
          <td>
            嘉義市
          </td>
          <td></td>
          <td>
            成立於2007年
          </td>
        </tr>
        <tr>
          <td>
            府城真樂軒八音樂團
          </td>
          <td>
            溫紹炳
          </td>
          <td>
            臺南市安平區文平路187巷113號<br>0929-281-694
          </td>
          <td></td>
          <td>
            成立於2005年
          </td>
        </tr>
        <tr>
          <td>
            南方優客八音樂團
          </td>
          <td>
            劉育玲
          </td>
          <td width="123">
            臺南市安平區文平路187巷113號<br>0937-613-610
          </td>
          <td>
            <a target="_" href="https://culture.tainan.gov.tw/table/index.php?m2=43">連結</a>
          </td>
          <td>
            成立於2016年
          </td>
        </tr>
        <tr>
          <td>
            竹頭背客家八音團
          </td>
          <td>
            鍾兆生
          </td>
          <td>
            高雄市美濃區廣興街121號<br>07-681-2538
          </td>
          <td>
            <a target="_" href="http://sixstar.moc.gov.tw/blog/KM6813819/knowHowFronListAction.do?method=doReadKnowHow&amp;source=3&amp;knowhowId=6602">連結</a>
          </td>
          <td>
            成立於2012年
          </td>
        </tr>
        <tr>
          <td>
            美濃福安國小八音班
          </td>
          <td>
            謝宜文
          </td>
          <td>
            高雄市美濃區中山路二段358號（美濃福安國小）<br>0932-837-873
          </td>
          <td></td>
          <td>
            成立於2006年
          </td>
        </tr>
        <tr>
          <td>
            美濃國中八音社
          </td>
          <td>
            指導老師<br>林作長
          </td>
          <td>
            高雄市美濃區中正路一段191號<br>07-681-6166
          </td>
          <td></td>
          <td>
            成立於2006年
          </td>
        </tr>
        <tr>
          <td>
            美濃客家八音團
          </td>
          <td>
            鍾彩祥
          </td>
          <td>
            高雄縣美濃鎮泰中路259巷23號<br>07-682-2348<br>0927-583-650
          </td>
          <td></td>
          <td>
            成立於2006年
          </td>
        </tr>
        <tr>
          <td width="75">
            美濃客家八音班
          </td>
          <td>
            謝宜文
          </td>
          <td>
            高雄市美濃區
          </td>
          <td></td>
          <td>
            成立於2008年
          </td>
        </tr>
        <tr>
          <td width="75">
            陳美子客家八音團
          </td>
          <td>
            陳美貴
          </td>
          <td>
            高雄市美濃區
          </td>
          <td></td>
          <td width="151"></td>
        </tr>
        <tr>
          <td>
            陸豐客家八音劇團
          </td>
          <td>
            梁盟政
          </td>
          <td>
            高雄市三民區鼎貴路72號<br>0938-706-972
          </td>
          <td>
            <a target="_" href="http://art-garden.khcc.gov.tw/introduction/team/31236">連結</a>
          </td>
          <td>
            成立於2003年
          </td>
        </tr>
        <tr>
          <td>
            大夥房藝術團
          </td>
          <td>
            團長<br>劉國政<br>聯絡人<br>徐淑芳
          </td>
          <td>
            屏東縣麟洛鄉新田村民族路234號<br>08-723-1258<br>0921-696-046
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/大夥房藝術團-1371254872966824/">連結</a>
          </td>
          <td>
            成立於2002年<br>練團時間：每週一、三、五15:00-21:00
          </td>
        </tr>
        <tr>
          <td>
            屏東縣八音協會
          </td>
          <td>
            鍾聰明
          </td>
          <td>
            屏東縣佳冬鄉六根村佳和路122號<br>08-866-2228
          </td>
          <td>
            <a target="_" href="https://thcdc.hakka.gov.tw/wSite/ct?xItem=3753&amp;ctNode=495&amp;mp=1">連結</a>
          </td>
          <td>
            成立於1988年
          </td>
        </tr>
        <tr>
          <td width="75">
            花蓮瑞穗漢聲文化樂團
          </td>
          <td>
            劉振君
          </td>
          <td>
            花蓮縣
          </td>
          <td></td>
          <td>
            成立於1997年
          </td>
        </tr>
      </tbody>
    </table>
    <br>
    <h3>
      三、客家傳統戲曲與表演形式
    </h3>
    <table rules="all" border="1" style="border:1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width:20%">名稱</th>
          <th style="width:20%">負責人</th>
          <th style="width:25%">地址/電話</th>
          <th>其他聯絡方式</th>
          <th style="width:25%">備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            紙風車劇團
          </td>
          <td>
            李永豐
          </td>
          <td>
            臺北市重慶南路二段59之2號2樓<br>02-2392-6170
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/paperwindmilltheatre/">連結</a>
          </td>
          <td>
            成立於1992年
          </td>
        </tr>
        <tr>
          <td>
            國立臺灣戲曲學院
          </td>
          <td>
            劉麗株
          </td>
          <td>
            臺北市文山區木柵路三段66巷8之1號<br>02-2936-7231#2551
          </td>
          <td>
            <a target="_" href="http://b017.tcpa.edu.tw/bin/home.php">連結</a>
          </td>
          <td>
            成立於2001年
          </td>
        </tr>
        <tr>
          <td>
            歡喜扮戲團
          </td>
          <td>
            林靜儀
          </td>
          <td>
            臺北市士林區德行西路97號2樓<br>02-8866-1116<br>02-8866-1090
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/UhanShiiTheatre/">連結</a>
          </td>
          <td>
            成立於1995年
          </td>
        </tr>
        <tr>
          <td>
            山宛然客家布袋戲團
          </td>
          <td>
            黃武山
          </td>
          <td>
            新北市板橋區縣民大道三段83號3樓<br>0932-330-003
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/山宛然客家布袋戲團-193976375896/">連結</a>
          </td>
          <td>
            成立於2002年
          </td>
        </tr>
        <tr>
          <td>
            戲偶子劇團
          </td>
          <td>
            邱豐榮
          </td>
          <td>
            新北市新店區達觀路38號2樓之6<br>0975-386-935
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/戲偶子劇團-123978480950659/">連結</a>
          </td>
          <td>
            成立於2003年
          </td>
        </tr>
        <tr>
          <td>
            景勝戲劇團
          </td>
          <td>
            江玉玲
          </td>
          <td>
            桃園市平鎮區大智街25號<br>03-457-8931<br>0935-129-811
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/景勝戲劇團-1657899551112033/">連結</a>
          </td>
          <td>
            成立於2003年
          </td>
        </tr>
        <tr>
          <td>
            貴鳳歌劇團
          </td>
          <td>
            陳鳳祺
          </td>
          <td>
            桃園縣龍潭鄉自由街51號<br>0911-241-388
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/a241388/">連結</a>
          </td>
          <td>
            成立於2002年
          </td>
        </tr>
        <tr>
          <td>
            新月娥歌劇團
          </td>
          <td>
            范姜新堯<br>劉雅如
          </td>
          <td>
            桃園市平鎮區大智街15號<br>03-458-0110<br>0933-507-453
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/新月娥歌劇團-334133613587392/">連結</a>
          </td>
          <td>
            成立於1961年
          </td>
        </tr>
        <tr>
          <td>
            德泰戲劇團
          </td>
          <td>
            李小平
          </td>
          <td>
            桃園市中壢區龍岡路三段243巷53弄36號<br>0919-362-104
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/a034586287/">連結</a>
          </td>
          <td>
            成立於1988年
          </td>
        </tr>
        <tr>
          <td>
            松興戲劇團
          </td>
          <td>
            林興松
          </td>
          <td>
            新竹縣北埔鄉中山路51號<br>0916-333-293
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/song.xing.opera/">連結</a>
          </td>
          <td>
            成立於2003年
          </td>
        </tr>
        <tr>
          <td>
            新永光歌劇團
          </td>
          <td>
            翁義富
          </td>
          <td>
            新竹縣竹北市十興里19鄰49號<br>03-550-3707<br>0922-721-880
          </td>
          <td></td>
          <td>
            成立於1962年
          </td>
        </tr>
        <tr>
          <td>
            新樂園戲劇團
          </td>
          <td>
            劉秀鳳
          </td>
          <td>
            新竹縣竹北市縣政三街19號<br>03-555-6358<br>0933-265-173
          </td>
          <td></td>
          <td>
            成立於2003年
          </td>
        </tr>
        <tr>
          <td>
            霓雲社客家三腳採茶戲團
          </td>
          <td>
            徐進堯
          </td>
          <td>
            新竹縣竹東鎮<br>03-582-2665
          </td>
          <td>
            <a target="_" href="mailto:Psz0952814938@yahoo.com.tw">連結</a>
          </td>
          <td>
            成立於1999年
          </td>
        </tr>
        <tr>
          <td>
            金滿圓戲劇團
          </td>
          <td>
            管建仲
          </td>
          <td>
            苗栗市福星里16鄰11之2號<br>03-773-0263
          </td>
          <td></td>
          <td></td>
        </tr>
        <tr>
          <td>
            苗栗縣客家曲藝推展協會
          </td>
          <td>
            謝其國
          </td>
          <td>
            苗栗縣頭屋鄉中山街5之1號<br>0937-813-833
          </td>
          <td></td>
          <td>
            成立於2005年
          </td>
        </tr>
        <tr>
          <td>
            榮興客家採茶劇團
          </td>
          <td>
            鄭月景
          </td>
          <td>
            苗栗市恭敬里4鄰24號<br>03-772-5099
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pg/romshinghakka/about/?ref=page_internal">連結</a>
          </td>
          <td>
            成立於1988年
          </td>
        </tr>
        <tr>
          <td>
            廖千盛布袋戲團
          </td>
          <td>
            廖千盛
          </td>
          <td>
            雲林縣二崙鄉崙東村仁和路142巷27號<br>05-598-8188
          </td>
          <td></td>
          <td>
            成立於 2013年
          </td>
        </tr>
        <tr>
          <td>
            廖千順布袋戲團
          </td>
          <td>
            廖千順
          </td>
          <td>
            雲林縣二崙鄉三和村三和路28之49號<br>0933-509-888
          </td>
          <td></td>
          <td>
            成立於2001年
          </td>
        </tr>
        <tr>
          <td>
            廖文和布袋戲團
          </td>
          <td>
            廖文和
          </td>
          <td>
            雲林縣二崙鄉紹興路19號<br>05-598-3777
          </td>
          <td></td>
          <td>
            成立於1976年
          </td>
        </tr>
        <tr>
          <td>
            走馬蓋文化藝術表演團
          </td>
          <td>
            楊秀春
          </td>
          <td>
            高雄市前鎮區崗山中街255號4樓之2<br>0931-616-986
          </td>
          <td></td>
          <td>
            成立於2004年
          </td>
        </tr>
        <tr>
          <td>
            哈旗鼓文化藝術表演團
          </td>
          <td>
            楊秀春
          </td>
          <td>
            高雄市前鎮區崗山中街255號4樓之1<br>0931-616-986
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/HaChiGu/">連結</a>
          </td>
          <td>
            成立於2004年
          </td>
        </tr>
        <tr>
          <td>
            世客文化藝術團
          </td>
          <td>
            吳川鈴
          </td>
          <td>
            屏東市豐田里水源巷12號<br>08-732-3202
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/世客文化藝術團-336912869758607/">連結</a>
          </td>
          <td>
            成立於2003年
          </td>
        </tr>
        <tr>
          <td>
            李文古歌劇團
          </td>
          <td>
            李盛發
          </td>
          <td>
            屏東縣內埔鄉內田村復興路38號<br>0932-882-984
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/LiWenGuGeJuTuan/">連結</a>
          </td>
          <td>
            成立於2003年
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
