<template>
  <div>
    <div class="title">
      <h2>流行音樂篇</h2>
    </div>
    <hr />
    <p class="firstRow"></p>
    <table rules="all" border="1" style="border: 1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width: 20%">名稱</th>
          <th style="width: 20%">負責人</th>
          <th style="width: 25%">其他聯絡方式</th>
          <th>備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            <p>吳青峰</p>
          </td>
          <td>
            <p>哈里坤的狂歡</p>
          </td>
          <td>
            <p>https://www.facebook.com/WuQingFeng/</p>
            <p>u.music@foxmail.com</p>
            <p>Oscar.lin@umusic.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>打幫你樂團</p>
          </td>
          <td>
            <p>Leo黎歐創意</p>
          </td>
          <td>
            <p>https://www.facebook.com/DaBangNi/</p>
            <p>dabangni@gmail.com</p>
          </td>
          <td>
            <p>成立於2011年12月</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>舒米恩</p>
          </td>
          <td>
            <p>亞神音樂</p>
          </td>
          <td>
            <p>https://www.sumingfans.com/</p>
            <p>johnsuming@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>蔡依林</p>
          </td>
          <td>
            <p>凌時差音樂</p>
          </td>
          <td>
            <p>https://www.facebook.com/hoo.jcai</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>姚宇謙</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>https://www.facebook.com/LowkingOfficial</p>
            <p>mail2elsa@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>蘇聖育</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>https://www.facebook.com/Sushenyu</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>黃子軒</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>https://www.facebook.com/zixuanslowtrain</p>
            <p>zixuanslowtrain@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>李宗盛</p>
          </td>
          <td>
            <p>李吉他</p>
          </td>
          <td>
            <p>http://tw.leeguitars.com/</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>滅火器</p>
          </td>
          <td>
            <p>火氣音樂</p>
          </td>
          <td>
            <p>https://www.facebook.com/FireEX</p>
            <p>info@fireonmusic.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>少女卡拉</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>https://www.facebook.com/siaulukhahlah</p>
            <p>https://www.instagram.com/siaulukhahlahofficial/</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>蘇慧倫</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>https://www.facebook.com/tarcysuofficial</p>
            <p>crystalresonance2010@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>黃妃</p>
          </td>
          <td>
            <p>勝駿娛樂</p>
          </td>
          <td>
            <p>https://www.facebook.com/HuangFei0713</p>
            <p>a_chefamily@yahoo.com.tw</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>劉若英</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>https://www.facebook.com/Rene0601/</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>羅時豐</p>
          </td>
          <td>
            <p>海蝶音樂</p>
          </td>
          <td>
            <p>https://www.facebook.com/profile.php?id=100044568693565</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>八三么</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>https://www.band831.com/</p>
            <p>https://www.facebook.com/band831tw</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>荒山亮</p>
          </td>
          <td>
            <p>勝駿娛樂</p>
          </td>
          <td>
            <p>https://www.facebook.com/HuangShanLiang</p>
            <p>a_chefamily@yahoo.com.tw</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>曹雅雯</p>
          </td>
          <td>
            <p>安樂茂思</p>
          </td>
          <td>
            <p>https://www.facebook.com/oliviatsao1130</p>
            <p>chun80900@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>陳永龍</p>
          </td>
          <td>
            <p>參拾柒度音樂</p>
          </td>
          <td>
            <p>https://www.facebook.com/yonlon.chen</p>
            <p>37domusic@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>潘越雲</p>
          </td>
          <td>
            <p>雲凱娛樂工作室</p>
          </td>
          <td>
            <p>https://www.facebook.com/潘越雲-Michelle-Pan-100447298213064</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>白安</p>
          </td>
          <td>
            <p>相信音樂</p>
          </td>
          <td>
            <p>https://www.facebook.com/baiannmusic</p>
            <p>jujistacy@gmail.com</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>5566</p>
          </td>
          <td>
            <p>喬傑立娛樂</p>
          </td>
          <td>&nbsp;</td>
          <td>
            <p>2009年單飛不解散</p>
          </td>
        </tr>
        <tr>
          <td>
            <p>羅大佑</p>
          </td>
          <td>
            <p>大右音樂</p>
          </td>
          <td>
            <p>https://www.facebook.com/LoTaYouOfficial</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>施文彬</p>
          </td>
          <td>
            <p>亂音製作</p>
          </td>
          <td>
            <p>https://www.facebook.com/rockapin</p>
            <p>k0938386665@yahoo.com.tw</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>任賢齊</p>
          </td>
          <td>
            <p>大岳娛樂</p>
          </td>
          <td>
            <p>https://www.facebook.com/richiefirework</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>謝宇威</p>
          </td>
          <td>
            <p>威德文化</p>
          </td>
          <td>
            <p>https://www.facebook.com/謝宇威-198419566895181</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>蕭敬騰</p>
          </td>
          <td>
            <p>喜鵲娛樂</p>
          </td>
          <td>
            <p>https://www.jamhsiao.com/</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>楊丞琳</p>
          </td>
          <td>
            <p>樹與天空娛樂</p>
          </td>
          <td>
            <p>https://www.facebook.com/0604rainie</p>
            <p>https://tw.weibo.com/3511727907</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>持修</p>
          </td>
          <td>
            <p>野聲音娛樂有限公司</p>
          </td>
          <td>
            <p>https://www.facebook.com/ChihSiou.L</p>
            <p>https://www.instagram.com/chih_siou/</p>
          </td>
          <td>&nbsp;</td>
        </tr>
        <tr>
          <td>
            <p>張惠妹</p>
          </td>
          <td>
            <p>聲動娛樂</p>
          </td>
          <td>
            <p>https://www.facebook.com/aMEI.feat.AMIT</p>
          </td>
          <td>&nbsp;</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>
