<template>
  <div>
    <div class="title">
      <h2>福佬歌謠篇</h2>
    </div>
    <hr>
    <p class="firstRow"></p>
    <table rules="all" border="1" style="border:1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width:20%">名稱</th>
          <th style="width:20%">負責人</th>
          <th style="width:25%">地址/電話</th>
          <th>其他聯絡方式</th>
          <th style="width:25%">備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            雨韻合唱團
          </td>
          <td>
            陳建宏
          </td>
          <td>
            基隆市安樂區樂利三街205號7樓
            <br />
            02-2425-3518
          </td>
          <td>
            <a target="_" href="http://www.yuyun.org.tw/yuyun/index.php/yuyun-about">連結</a>
          </td>
          <td>
            1960年成立於基隆市，是基隆第一個社會合唱團體。
          </td>
        </tr>
        <tr>
          <td>
            基隆啄木鳥合唱團
          </td>
          <td>
            陳吉宗
          </td>
          <td>
            基隆市仁愛區仁二路58號
            <br />
            02-2423-4884
          </td>
          <td>
            <a
              target="_"
              href="https://www.facebook.com/pages/category/Performing-Arts/基隆市啄木鳥合唱團粉絲團-516315805193598/"
              >連結</a
            >
          </td>
          <td>
            1985年成立於基隆，是由一群熱愛合唱的男士所組成。成立宗旨為「以雄壯渾厚、優美溫醇之男聲合唱，來洗滌人心，並形塑社會之善良風氣」。
          </td>
        </tr>
        <tr>
          <td>
            基隆愛樂合唱團
          </td>
          <td>
            莊瑾潔
          </td>
          <td>
            基隆市仁愛區仁二路119巷13之4號1樓
            <br />
            02-2425-5289
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/KeelungPhilharmonicChoir/">連結</a>
          </td>
          <td>
            1975年成立，前身為基隆商工校友合唱團。近年來以多元創新的表演形態，推出多齣合唱音樂劇。
          </td>
        </tr>
        <tr>
          <td>
            龤之聲男聲合唱團
          </td>
          <td>
            陳建豪
          </td>
          <td>
            臺北市大同區民生西路176號3樓<br />

            0933-935-303
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pg/hsieh.jsc/about/?ref=page_internal"
              >連結</a
            >
          </td>
          <td>
            成立於2006年，最初由基隆高中「龤韻合唱團」畢業校友所組成，將「快快樂樂地唱歌，唱出無國界的聲音」，訂為創團後永續發展的目標，也藉和「龤」的「聲」音，作為團員之間最大的共鳴，因而正式命名為「龤之聲男聲合唱團」。是基隆當地最年輕的男聲合唱團。
          </td>
        </tr>
        <tr>
          <td>
            長春花樂團
          </td>
          <td>
            陳明章、阿桃家族
          </td>
          <td>
            臺北市北投區開明街71號
            <br />
            02-2893-3088
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/長春花樂團桃花團-1061906727227527/"
              >連結</a
            >
          </td>
          <td>
            成立於2015年。長春花樂團成員全由來自各地的臺灣月琴民謠協會學員所組成。
          </td>
        </tr>
        <tr>
          <td>
            臺灣月琴民謠協會
          </td>
          <td>
            陳明章
          </td>
          <td>
            臺北市北投區開明街71號
            <br />
            02-2893-3088
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/Taiwan.yueqin/">連結</a>
          </td>
          <td>
            成立於2009年，發起人為陳明章，他集合熱衷致力推廣月琴之會員，讓臺灣的國民樂器「月琴」能繼續被傳承與演奏。
          </td>
        </tr>
        <tr>
          <td>
            灣聲樂團
          </td>
          <td>
            李哲藝
          </td>
          <td>
            臺北市中正區館前路34號11樓
          </td>
          <td>
            <a target="_" href="http://www.onesongorchestra.com">連結</a>
          </td>
          <td>
            2017年李哲藝所創，是臺灣第一個、也是專門演出臺灣音樂作品的團體。<br />

            主要演出的音樂包括兩種：一是臺灣人所寫的音樂，二是以臺灣為素材所寫的音樂。目的是要將「古典音樂臺灣化，臺灣音樂古典化」。
          </td>
        </tr>
        <tr>
          <td>
            夏至愛樂大提琴室內樂團
          </td>
          <td>
            王夙慧
          </td>
          <td>
            臺北市大安區永康里麗水街9巷10號6樓
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/stringcello">連結</a>
          </td>
          <td>
            成立於2013年。利用每週固定團練，互相交流、成長，也希望藉由演出，讓更多人愛上音樂。
          </td>
        </tr>
        <tr>
          <td>
            福爾摩沙合唱團
          </td>
          <td>
            蘇慶俊
          </td>
          <td>
            臺北市中山區民權東路二段61號2樓
          </td>
          <td>
            <a target="_" href="http://formosasingers.org.tw/index.php">連結</a>
          </td>
          <td>
            1994年由愛樂牧歌合唱團重新改組而成，為一混聲合唱團，以推廣優質臺灣合唱音樂、追求精緻化合唱藝術為宗旨。
          </td>
        </tr>
        <tr>
          <td>
            師友合唱團
          </td>
          <td>
            曾惠君
          </td>
          <td>
            臺北市文山區景文街89號4樓
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/shihyuchorus/">連結</a>
          </td>
          <td>
            前身為「臺灣師範大學校友合唱團」，2005年成立「師友合唱團」。近年持續辦理慈善暨公益巡迴演唱，關懷弱勢族群與團體。
          </td>
        </tr>
        <tr>
          <td>
            台大合唱團
          </td>
          <td>
            胡昇旻
          </td>
          <td>
            臺北市大安區羅斯福路四段85號
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/NTUChorus/posts/10155879512206450/"
              >連結</a
            >
          </td>
          <td>
            前身為友愛合唱團，成立於光復初年，後擴大為純誼合唱團與法學院合唱團，1964年合併，更名為「國立臺灣大學合唱團」，簡稱台大合唱團。
          </td>
        </tr>
        <tr>
          <td>
            台北心聲合唱團
          </td>
          <td>
            劉紹棟
          </td>
          <td>
            臺北市中山區北安路589號5樓
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/taipeiharmonicchorus/">連結</a>
          </td>
          <td>
            中興法商心聲合唱團成立於1956年，2005年改名為「台北心聲合唱團」，並向臺北市政府文化局申請立案，成為正式演藝團體，定期舉辦音樂會。曾多次獲得臺北市文化局之藝文補助。
          </td>
        </tr>
        <tr>
          <td>
            台北基督教兒童合唱團團友隊
          </td>
          <td>
            林惠美
          </td>
          <td>
            臺北市北投區西安街一段175號2樓
          </td>
          <td>
            <a
              target="_"
              href="https://www.facebook.com/Taipei-Christian-Children-Chorus-95361510268/"
              >連結</a
            >
          </td>
          <td>
            自幼受林福裕的啟蒙而熱愛合唱；15年來持續合唱的傳統，傳唱林福裕的作品，並不時演繹其他膾炙人口的各類歌曲。
          </td>
        </tr>
        <tr>
          <td>
            台北室內50合唱團
          </td>
          <td>
            方素貞
          </td>
          <td>
            臺北市大安區敦化南路一段159號3樓
          </td>
          <td>
            <a target="_" href="http://www.tcschoir.org.tw/news">連結</a>
          </td>
          <td>
            成立於2011年，是台北室內合唱團第二支附屬團隊，台北室內合唱團推廣合唱藝術的重要推手。
          </td>
        </tr>
        <tr>
          <td>
            臺大星韻合唱團
          </td>
          <td>
            陳蘋
          </td>
          <td>
            臺北市大安區羅斯福路四段1號
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/NTUStarRhythmChorus">連結</a>
          </td>
          <td>
            1975年成立，不僅擁有多元背景的團員，演出曲目也相當豐富，橫跨古今、各類小品與無伴奏歌曲都有涉獵。
          </td>
        </tr>
        <tr>
          <td>
            凡響管絃樂團暨青少年管絃樂團
          </td>
          <td>
            李室春
          </td>
          <td>
            臺北市大安區羅斯福路三段67號1樓
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/sonare1821/">連結</a>
          </td>
          <td>
            成立於2000年，積極與臺灣著名演奏家合作，並定期演出本土音樂作品、推廣臺灣當代創作音樂，期盼將臺灣音樂拓展至世界舞臺。
          </td>
        </tr>
        <tr>
          <td>
            小巨人絲竹樂團
          </td>
          <td>
            陳佳瑜
          </td>
          <td>
            臺北市中正區汀州路一段226巷15號4樓之1
          </td>
          <td>
            <a target="_" href="https://www.littlegiant.idv.tw/">連結</a>
          </td>
          <td>
            成立於2000年，積極推廣國樂，並舉辦一系列「兩岸薪傳」、「絲竹室內樂」及「青年演奏家」音樂會等。自2005年起連續獲選為文化部演藝扶植團隊，並獲得政府及民間單位的藝文經費補助，在藝術表現上備受肯定。
          </td>
        </tr>
        <tr>
          <td>
            福爾摩沙淡水走唱團
          </td>
          <td>
            陳明章
          </td>
          <td>
            臺北市北投區開明街71號
          </td>
          <td>
            <a target="_" href="https://www.cmcmusic.com.tw/福爾摩沙淡水走唱團/">連結</a>
          </td>
          <td>
            由陳明章、金門王、李炳輝等人創立於1996年。致力於將臺灣各地的文化融入歌曲中，傳唱屬於臺灣獨特的民謠。
          </td>
        </tr>
        <tr>
          <td>
            悅聲合唱團
          </td>
          <td>
            賴滿足
          </td>
          <td>
            臺北市南京東路五段16號5樓之2
          </td>
          <td>
            <a target="_" href="https://elearning.canceraway.org.tw/pagelist.asp?keyid=47">連結</a>
          </td>
          <td>
            1997年成立，成員包括癌症患者、癌症家屬以及社會上各階層人士，其中三分之一是癌症病人，此為這個團體很大的特色。悅聲合唱團秉持著「自助、互助、助人」的信念，扶持每位病友勇敢邁向康復之路，同時將自身抗癌經歷化作歌聲，鼓勵正與病魔對抗的朋友們，熱愛生命、永不放棄。
          </td>
        </tr>
        <tr>
          <td>
            蕙德藝術團
          </td>
          <td>
            吳達德
          </td>
          <td>
            臺北市南港區三重路17號1樓
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/TheTalta/">連結</a>
          </td>
          <td>
            成立於2017年，由愛好音樂自小學習小提琴的日本國立東京大學醫學博士吳達德醫師所創。成立宗旨為演出傳統唸歌藝術文化，延續並發揚傳統藝術的傳承；以臺語唱出臺灣優美的歌謠，讓世界認識臺灣歌謠之美。
          </td>
        </tr>
        <tr>
          <td>
            直締友聲室內合唱團
          </td>
          <td>
            蘇嘉冠
          </td>
          <td>
            臺北市北投區中央北路四段416號一樓
          </td>
          <td>
            <a target="_" href="http://langeracq.wordpress.com/">連結</a>
          </td>
          <td>
            前身為「大直高中校友合唱團」，2005年成立，2008年更名為「直締友聲室內合唱團」，2012年正式成為政府立案登記之演藝團體，並逐年推出系列音樂會，或參與友團之音樂聯演。
          </td>
        </tr>
        <tr>
          <td>
            新逸交響樂團
          </td>
          <td></td>
          <td>
            臺北市士林區劍潭路42號1樓
          </td>
          <td>
            <a target="_" href="https://www.newartinc.org">連結</a>
          </td>
          <td>
            新逸交響樂團一直以來，用音樂來贊助、支持需要幫助的弱勢團體，並配合公益音樂會的呈現，給年輕音樂家舞臺並進而用音樂行善。
          </td>
        </tr>
        <tr>
          <td>
            迴響國樂團
          </td>
          <td>
            張俊彥
          </td>
          <td>
            臺北市松山區延壽街337之2號4樓
          </td>
          <td>
            <a
              target="_"
              href="https://www.facebook.com/pages/category/Musician-Band/262705720745204/"
              >連結</a
            >
          </td>
          <td>
            成立自2006年，由一群國樂愛好者組成，2010年正式隸屬於臺北市新竹縣同鄉會，並順利進入臺北市政府客委會教育中心，得到客委會鼎力支持與輔導，多年來接受各方邀約演出，廣受好評。
          </td>
        </tr>
        <tr>
          <td>
            卡到音即興樂團
          </td>
          <td>
            李世揚
          </td>
          <td>
            新北市三重區三和路2段208號4樓之3
          </td>
          <td>
            <a
              target="_"
              href="https://www.facebook.com/pages/category/Performing-Arts/Ka-Dao-Yin-aka-Caught-Up-In-144189072312074/"
              >連結</a
            >
          </td>
          <td>
            卡到音即興樂團將即興的創作方法和現代音樂特性融入作品，並且混編古箏、笙、鋼琴、薩克斯風等中西樂器，期待將更多元的音樂面貌呈現給大衆。
          </td>
        </tr>
        <tr>
          <td>
            民視臺灣學堂
          </td>
          <td></td>
          <td>
            新北市林口區信義路99號
          </td>
          <td>
            <a target="_" href="https://taiwanlecturehall.com.tw">連結</a>
          </td>
          <td>
            電視史上第一個論述臺灣的課程－《民視臺灣學堂》，探討學門包括歷史、法律、宗教、哲學、藝術等，有最堅強的師資陣容，是最道地的臺灣聲音。
          </td>
        </tr>
        <tr>
          <td>
            田園樂府
          </td>
          <td>
            簡上仁
          </td>
          <td>
            新北市淡水區紅樹林路195號8樓<br />

            02-3758-0272
          </td>
          <td>
            <a
              target="_"
              href="https://www.facebook.com/pages/category/Musician-Band/田園樂府樂團-222806804410296/"
              >連結</a
            >
          </td>
          <td>
            是一個以維護與發揚臺灣音樂文化為目的的音樂文化團體。1983年由簡上仁創辦。
          </td>
        </tr>
        <tr>
          <td>
            楊秀卿說唱藝術團
          </td>
          <td>
            楊火土
          </td>
          <td>
            新北市汐止區汐萬路二段37巷3號3樓
            <br />
            02-2646-3947
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/showking317/">連結</a>
          </td>
          <td>
            2010年楊秀卿成立，楊秀卿為國家指定登錄重要傳統藝術說唱保存者。
          </td>
        </tr>
        <tr>
          <td>
            嵐韻合唱團
          </td>
          <td>
            曾文正
          </td>
          <td>
            新北市新莊區龍安路66之38號2樓
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/LanYunChorus/">連結</a>
          </td>
          <td>
            嵐韻合唱團前身為復興高中校友合唱團。
          </td>
        </tr>
        <tr>
          <td>
            心韻合唱團
          </td>
          <td>
            謝秋瑛
          </td>
          <td>
            新北市板橋區莊敬路152號
          </td>
          <td>
            <a target="_" href="http://www.singwing.org.tw">連結</a>
          </td>
          <td>
            成立於1990年，由一群肢障者和幾位熱情的社青朋友所組成。成立宗旨為結合肢障青年與愛樂社青，培養音樂的才華，合群的美德。
          </td>
        </tr>
        <tr>
          <td>
            拉縴人男聲合唱團
          </td>
          <td></td>
          <td>
            新北市新店區北新路三段205之3號7樓B室
          </td>
          <td>
            <a target="_" href="http://www.tmccaf.org.tw">連結</a>
          </td>
          <td>
            前身為成立於1980年代末的「成功高中校友合唱團」，1998年立案為演藝團隊，正式更名為「拉縴人男聲合唱團」。
          </td>
        </tr>
        <tr>
          <td>
            台灣唸歌團
          </td>
          <td>
            邱文錫
          </td>
          <td>
            新北市中和區南工路10巷6號
          </td>
          <td></td>
          <td>
            前身是洪瑞珍於2002年創立的洪瑞珍唸歌團。後多位洪瑞珍的學生和各路同好乃於2009年重新創立台灣唸歌團，主要目的是要從事月琴唸歌的傳承工作，希望透過他們的努力，讓這項臺灣的傳統文化更加發揚光大。
          </td>
        </tr>
        <tr>
          <td>
            微笑唸歌團
          </td>
          <td>
            儲見智
          </td>
          <td>
            臺中市北區錦中街25號
            <br />
            0953-724-857
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/taiwansmile/">連結</a>
          </td>
          <td>
            成立於2011年，創辦人為儲見智與林恬安，以傳承推廣唸歌文化為主要宗旨，藉由唸歌的演出、展覽、教學、演講等方式，傳達臺語說唱藝術的理念。
          </td>
        </tr>
        <tr>
          <td>
            幕聲合唱團
          </td>
          <td>
            吳念芝
          </td>
          <td>
            臺中市北屯區雷中街19巷7號4樓之1
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/tabernacle.choir">連結</a>
          </td>
          <td>
            2006年成立。2010年獲第六屆世界合唱大賽金牌、2012年獲日本寶塚第二十八屆國際室內合唱大賽戲劇組及浪漫組金牌。
          </td>
        </tr>
        <tr>
          <td>
            大甲愛樂室內樂團
          </td>
          <td>
            鄭宥媃
          </td>
          <td>
            臺中市大甲區三民路141號
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/dajiamusic98/">連結</a>
          </td>
          <td>
            是由中部音樂家組成的室內樂團，耕耘音樂演出及音樂教育推廣逾十年。除致力於展現音樂的多元樣貌外，也將耳熟能詳的旋律重新改編，結合導聆與現場演出的方式，拉近聽眾與演出者的距離。
          </td>
        </tr>
        <tr>
          <td>
            旭陽民俗車鼓劇團
          </td>
          <td>
            吳現山
          </td>
          <td>
            雲林縣土庫鎮
          </td>
          <td></td>
          <td>
            成立於1973年。創始人吳天羅，1999年獲頒「民俗藝術終身成就獎」。吳天羅逝世後，其兒女繼承衣缽，現任團長為其子吳現山。
          </td>
        </tr>
        <tr>
          <td>
            高雄市交響樂團附設青少年交響樂團
          </td>
          <td>
            涂惠民
          </td>
          <td>
            高雄市鳳山區光遠路161號
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/pg/kso.taiwan/about/?ref=page_internal"
              >連結</a
            >
          </td>
          <td>
            成立於2004年，是全臺最具規模的青少年學生樂團。2013年起為提供更專業的樂團訓練，更名為「高雄市交響樂團附設青少年交響樂團」。2015年起，每年受邀於南部藝文盛會「高雄春天藝術節KSAF」演出，與高雄市優秀青少年舞者合作，演繹多部經典作品，精緻高規格的製作屢獲佳評。
          </td>
        </tr>
        <tr>
          <td>
            高雄室內合唱團
          </td>
          <td>
            翁佳芬
          </td>
          <td>
            高雄市苓雅區憲政路235號
          </td>
          <td>
            <a
              target="_"
              href="https://www.facebook.com/pages/category/Musician-Band/Kaohsiung-Chamber-Choir-161258233928570/"
              >連結</a
            >
          </td>
          <td>
            成立於2002年，由一群熱愛精緻藝術音樂的合唱人組成，多年來已為南臺灣合唱音樂環境，注入了一股精緻化的新力量，並期待繼續引領南臺灣的合唱音樂，走向更專業化的發展。
          </td>
        </tr>
        <tr>
          <td>
            恆春民謠促進會
          </td>
          <td>
            陳麗萍
          </td>
          <td>
            屏東縣恆春鎮中正路146號
            <br />
            08-889-8166
          </td>
          <td>
            <a target="_" href="http://web.hcps.ptc.edu.tw/cyberfair2006/G/g2.htm">連結</a>
          </td>
          <td>
            民歌採集運動發現陳達後，掀起了一陣恆春民謠熱潮。隨著陳達的過世，地方上的長官們，有感於這種深具地方特性的民謠若沒傳下來，恐將隨著歲月的凋零而失落，於是就與當地有心人士，共同成立「恆春思想起民謠促進會」，以推廣恆春民謠。現任團長為高李正姬任，總幹事為趙振英。
          </td>
        </tr>
        <tr>
          <td>
            恆春民謠館
          </td>
          <td>
            屏東縣政府
          </td>
          <td>
            屏東縣恆春鎮恆南路168號
            <br />
            08-888-0293
          </td>
          <td>
            <a
              target="_"
              href="https://www.facebook.com/pages/category/Travel-Service/424690274297349/"
              >連結</a
            >
          </td>
          <td>
            2009年揭牌啟用。2008年屏東縣政府向恆春旅遊醫院租用舊有宿舍作為「恆春民謠館」。
          </td>
        </tr>
        <tr>
          <td>
            滿州民謠協進會
          </td>
          <td>
            滿州鄉公所
          </td>
          <td>
            屏東縣滿州鄉滿州村中山路43號
            <br />
            08-880-1105
          </td>
          <td>
            <a
              target="_"
              href="https://www.pthg.gov.tw/townmto/Content_List.aspx?n=1D48F4EE0338DF0B"
              >連結</a
            >
          </td>
          <td>
            1981年正式成立
          </td>
        </tr>
        <tr>
          <td>
            滿州民謠館
          </td>
          <td>
            滿州鄉公所
          </td>
          <td>
            屏東縣滿州鄉滿州村中山路43號
            <br />
            08-880-1105
          </td>
          <td>
            <a
              target="_"
              href="https://www.pthg.gov.tw/townmto/Content_List.aspx?n=1D48F4EE0338DF0B"
              >連結</a
            >
          </td>
          <td>
            2018年2月16日開幕
          </td>
        </tr>
      </tbody>
    </table>
    <br clear="all" />
    <table rules="all" border="1" style="border:1px solid" cellpadding="5">
      <thead>
        <tr>
          <th style="width:20%">名稱</th>
          <th style="width:25%">地址/電話</th>
          <th style="width:25%">其他聯絡方式</th>
          <th>備註</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>
            丁秀津
          </td>
          <td>
            臺北市
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/Melodysyueqin/">連結</a>
          </td>
          <td>
            唸歌仔藝人。文化部指定「重要無形文化資產保存者」楊秀卿之第二屆傳習藝生。
          </td>
        </tr>
        <tr>
          <td>
            陳明章
          </td>
          <td>
            臺北市北投區
          </td>
          <td></td>
          <td>
            1956-，音樂創作人、音樂製作人、歌手、吉他與月琴演奏家、黑膠唱片收藏家。1987年法國南特影展上，《戀戀風塵》獲得最佳電影配樂，之後便經常為電影、紀錄片製作音樂。
          </td>
        </tr>
        <tr>
          <td>
            陳維斌
          </td>
          <td>
            臺北市
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/DenxTaiwanMusic/">連結</a>
          </td>
          <td>
            臺語歌曲詞曲作家、醫生。
          </td>
        </tr>
        <tr>
          <td>
            鄭美
          </td>
          <td>
            臺北市
          </td>
          <td></td>
          <td>
            唸歌仔藝人。文化部指定「重要無形文化資產保存者」楊秀卿之第一屆結業藝生。
          </td>
        </tr>
        <tr>
          <td>
            楊秀卿
          </td>
          <td>
            新北市汐止區
          </td>
          <td></td>
          <td>
            1935-，國寶級唸歌仔藝人。1989年獲教育部頒發民族說唱藝術「薪傳獎」，2007年獲國家文化藝術基金會頒發第十一屆「國家文藝獎」，2009年獲文建會指定為「第一屆重要傳統藝術說唱類保存者」，同年亦成為臺北縣市政府合聘的「第一屆臺北傳統藝術榮譽藝師」，在臺灣說唱藝術界獲得至高無上的榮譽。2010年文化部文化資產局指定其為「重要無形文化資產」保存藝師。
          </td>
        </tr>
        <tr>
          <td>
            簡上仁
          </td>
          <td>
            新北市淡水區<br />

            02-3758-0272
          </td>
          <td></td>
          <td>
            1948-，詞曲創作、演唱者、民族音樂研究者。長期致力於臺灣本土音樂之採集、整理、創作及推展工作，1983年成立「田園樂府」樂團並擔任團長至今。<br />

            曾獲關懷臺灣人文社會貢獻獎、第廿四屆中興文藝獎章音樂獎、國立清華大學傑出教學獎、第十一屆全球華人藝術文化薪傳獎等獎項。
          </td>
        </tr>
        <tr>
          <td>
            陳寶貴
          </td>
          <td>
            新竹縣
          </td>
          <td></td>
          <td>
            1939-，唸歌仔說唱藝人。2016年和陳美珠同時被新北市政府指定登錄為新北市說唱傳統表演藝術保存者。
          </td>
        </tr>
        <tr>
          <td>
            林恬安
          </td>
          <td>
            臺中市潭子區
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/taiwansmile/">連結</a>
          </td>
          <td>
            擅長唸歌仔。與儲見智共同成立微笑唸歌團。文化部指定「重要無形文化資產保存者」楊秀卿之第二屆傳習藝生。
          </td>
        </tr>
        <tr>
          <td>
            儲見智
          </td>
          <td>
            臺中市潭子區
            <br />
            0953-724-857
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/taiwansmile/">連結</a>
          </td>
          <td>
            1976-，擅長唸歌仔，微笑唸歌團團長。文化部指定「重要無形文化資產保存者」楊秀卿之第二屆傳習藝生。
          </td>
        </tr>
        <tr>
          <td>
            李哲藝
          </td>
          <td>
            高雄市
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/harpjoe.lee">連結</a>
          </td>
          <td>
            曾獲臺灣傳統藝術類金曲獎最佳作曲人、最佳創作人的獎項，他的作品涵蓋古典交響、爵士、流行、音樂舞臺劇、兒童劇；京劇、崑曲、粵劇、歌仔戲等，是一位全方位的創作者。<br />

            現為宙斯愛樂管弦樂團音樂總監暨駐團作曲家，並任這個樂團室內管弦樂團常任指揮、簧族單簧管重奏客席指揮，以及灣聲樂團團長，致力於詮釋臺灣作曲家的作品及以臺灣文化素材創作的作品。
          </td>
        </tr>
        <tr>
          <td>
            張日貴
          </td>
          <td>
            屏東縣滿州鄉
          </td>
          <td>
            <a target="_" href="http://musiciantw.ncfta.gov.tw/list.aspx?p=M064&amp;c=&amp;t=1"
              >連結</a
            >
          </td>
          <td>
            1933-，滿州鄉民謠歌手、民謠傳藝師。2012年獲選文化部「重要傳統藝術－滿州民謠保存者」，之後受聘擔任傳藝師。
          </td>
        </tr>
        <tr>
          <td>
            許麗善
          </td>
          <td>
            屏東縣滿州鄉
          </td>
          <td></td>
          <td>
            1965-，擅長滿州民謠。文化部指定「重要無形文化資產保存者」張日貴之傳習藝生。現任屏東縣屏南社區大學副校長。
          </td>
        </tr>
        <tr>
          <td>
            黎竹紅
          </td>
          <td>
            屏東縣滿州鄉
          </td>
          <td></td>
          <td>
            1959-，擅長滿州民謠。文化部指定「重要無形文化資產保存者」張日貴之傳習藝生。
          </td>
        </tr>
        <tr>
          <td>
            張碧英
          </td>
          <td>
            屏東縣滿州鄉
          </td>
          <td></td>
          <td>
            滿州民謠國寶級藝師張日貴的結業藝生，也是滿州民謠的重要推手之一。
          </td>
        </tr>
        <tr>
          <td>
            張錦桂
          </td>
          <td>
            屏東縣滿州鄉
          </td>
          <td></td>
          <td>
            滿州民謠國寶級藝師張日貴的結業藝生。隨張日貴學習民謠吟唱，紮下根基，埋下滿州民謠的種子。
          </td>
        </tr>
        <tr>
          <td>
            王洋月
          </td>
          <td>
            屏東縣滿州鄉
          </td>
          <td>
            <a target="_" href="https://www.facebook.com/people/王洋月/100033827504203">連結</a>
          </td>
          <td>
            滿州民謠協進會理事長
          </td>
        </tr>
        <tr>
          <td>
            黃靜慧
          </td>
          <td>
            屏東縣滿州鄉
          </td>
          <td></td>
          <td>
            滿州民謠協進會總幹事
          </td>
        </tr>
        <tr>
          <td>
            劉逸群
          </td>
          <td></td>
          <td></td>
          <td>
            主修二胡。曾任明華園歌仔戲團等之後場樂師、宜蘭高商等中小學教師。
          </td>
        </tr>
        <tr>
          <td>
            周玉湘
          </td>
          <td></td>
          <td></td>
          <td>
            國立臺南藝術大學七年一貫制中國音樂學系畢業，主修琵琶。2018年考取文化部「重要傳統表演藝術說唱－楊秀卿傳習計畫」藝生，成為楊秀卿之傳習藝生。
          </td>
        </tr>
      </tbody>
    </table>

  </div>
</template>
